version: '3'
services:
  web:
    build: .
    image: kijiji-manager
    volumes:
      - ./instance:/app/instance
    ports:
      - "5000:80"
#    environment:
#      # Example of defining a custom config file location using the 'CONFIG_FILE' environment variable
#      # Config files should still be within the instance folder since it is accessible as a volume within the container
#      - CONFIG_FILE=instance/custom-config.cfg
